import { Asset } from '@/types'

export const mockAssets: Asset[] = [
  {
    id: '1',
    name: '台積電',
    type: '股票',
    amount: 100,
    cost: 500000,
    current_price: 550,
    market_value: 55000,
    profit: 5000,
    profit_percentage: 10,
    last_updated: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bitcoin',
    type: '加密貨幣',
    amount: 0.5,
    cost: 600000,
    current_price: 1300000,
    market_value: 650000,
    profit: 50000,
    profit_percentage: 8.33,
    last_updated: new Date().toISOString(),
  },
  {
    id: '3',
    name: '定期存款',
    type: '現金',
    amount: 1,
    cost: 100000,
    current_price: 100000,
    market_value: 100000,
    profit: 0,
    profit_percentage: 0,
    last_updated: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Apple Inc.',
    type: '股票',
    symbol: 'AAPL',
    amount: 100,
    cost: 150,
    current_price: 175,
    market_value: 17500,
    profit: 2500,
    profit_percentage: 16.67,
    last_updated: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'USDT',
    type: '現金',
    symbol: 'USDT',
    amount: 10000,
    cost: 1,
    current_price: 1,
    market_value: 10000,
    profit: 0,
    profit_percentage: 0,
    last_updated: new Date().toISOString(),
    notes: 'USD'
  },
  {
    id: '6',
    name: 'ETH-USDT LP',
    type: 'defi',
    symbol: 'ETH-USDT',
    amount: 1000,
    cost: 1,
    current_price: 1.2,
    market_value: 1200,
    profit: 200,
    profit_percentage: 20,
    last_updated: new Date().toISOString(),
    notes: JSON.stringify({
      protocol: 'Uniswap V3',
      type: 'Liquidity Pool',
      blockchain: 'Ethereum',
      apy: '25%',
      healthFactor: '2.5',
      riskLevel: '中'
    })
  },
  {
    id: '7',
    name: 'ETH',
    type: 'wallet',
    symbol: 'ETH',
    amount: 2,
    cost: 2000,
    current_price: 3000,
    market_value: 6000,
    profit: 2000,
    profit_percentage: 50,
    last_updated: new Date().toISOString(),
    notes: JSON.stringify({
      address: '0x1234...5678',
      blockchain: 'Ethereum'
    })
  }
] 